version: 2

sources:
  - name: google_analytics_4
    schema: google_analytics_4
    tables:
      - name: events_20210131
      
  - name: us_google_sheets
    schema: us_google_sheets
    tables:
      - name: account_manager_region_mapping

  - name: sales_database
    schema: sales_database
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user